# This first module extracts a shear catalog from the simulation
extract_footprint:

    # DESCQA GCR catalog descriptor
    catalog: proto-dc2_v2.0

    # Type of footprint
    # This is optional, if not provided, the entire simulation will be outputed
    #footprint:
    #  type: patch
    #  ra_range:  [0, 5]
    #  dec_range: [0, 5]

    # Optionally, specify some truth fields to save beyond the default ones
    # Default ones: ['galaxy_id', 'ra', 'dec', 'ra_true', 'dec_true', 'shear_1', 'shear_2', 'convergence', 'redshift']
    export_quantities: []
