launcher: cori-interactive

modules: mmpipe

stages:
    - name: extractFootprintPipe
      nprocess: 1
    - name: mockShearMeasurementPipe
      nprocess: 1
    - name: shearMapPipe
      nprocess: 1
    - name: convergenceMapPipe
      nprocess: 1

output_dir: ./outputs

inputs:
    config: configs/config.yml
resume: True
log_dir: ./test/logs
pipeline_log: log.txt
