# This demo config file illustrates how to produce a mass map


# This module applies cuts to the input catalog
selection:

    # Input
    input_filename: hsc_output/tract008766-test-medsdm-dbcoadd-mcal-001.fits

    # Specifies the cuts to apply
    cuts:
        - shape['flags'] == 0
        - shape['mcal_s2n_r'] > 10
        - (shape['mcal_T'] / shape['psfrec_T']) > 0.5

    # Ouput
    output_filename: hsc_output/shape_catalog.fits

# This first module computes a shear map from the provided shape catalog
shear_map:

    # Input
    input_filename: hsc_output/shape_catalog.fits

    # Defines the projection to use (could also be HEALpix)
    projection:
        type: 'gnomonic'
        center_ra: 35.7  # In deg
        center_dec: -3.7 # In deg
        pixel_size: 1 # In arcmin
        nx: 128
        ny: 128

    # Output folder for the catalog
    output_filename: hsc_output/shear_map.fits

# The second module computes a convergence map from the input shear map
convergence_map:
    # Input
    input_filename: hsc_output/shear_map.fits

    # Type and parameters of mass-mapping algorithm
    algorithm:
        name: 'flat_ks'
        # smoothing: 1 # Gaussian smoothing in arcmin
        # zero_padding: 128 # Size of the zero_padding region for inversion

    output_filename: hsc_output/convergence_map.fits
