# This demo config file illustrates how to produce a mass map

#
# TODO: Add a module to apply cuts
#

# This first module computes a shear map from the provided shape catalog
shear_map:

    # Input
    input_directory: mock_output
    input_filename: 'shape_catalog.fits'

    # Defines the projection to use (could also be HEALpix)
    projection:
        type: 'Gnomonic'
        center_ra: 35.7  # In deg
        center_dec: -3.7 # In deg
        pixel_size: 1 # In arcmin
        nx: 128
        ny: 128

    # Output folder for the catalog
    output_directory: mock_output
    output_filename: shear_map.fits

# The second module computes a convergence map from the input shear map
convergence_map:
    # Input
    input_directory: mock_output
    input_filename: 'shear_map.fits'

    # Type and parameters of mass-mapping algorithm
    algorithm:
        name: 'flat_ks'
        # smoothing: 1 # Gaussian smoothing in arcmin
        # zero_padding: 128 # Size of the zero_padding region for inversion

    output_directory: mock_output
    output_filename: 'convergence_map.fits'
