TXGCRTwoCatalogInput:

    cat_name: dc2_object_run2.1.1i_with_metacal.yaml

TXSelector:
  T_cut: 0.1
  s2n_cut: 0.1
  delta_gamma: 0.01
  zbin_edges: [0.0, 2.0]

shearMapPipe:
    center_ra: 62.3
    center_dec: -35.75
    pixel_size: 0.5
    nx: 800
    ny: 800