mock_observation:

    # Whether to use shear or reduced shear [mandatory]
    reduced_shear: false

    # Type of shape noise to use
    # Here a simple Gaussian, but could also use the shapes provided in the
    # simulation [optional]
    shape_noise:
      # Simple Gaussian noise to start with
      type: Gaussian
      # Per component standard deviation of the noise
      sigma: 0.13

    # TODO: Add option for masking
    # TODO: Add option for photo-z
    # TODO: Add some mechanism to process the data in chunks or it wont fit in memory

    # Could have several types of mocks, like im3shape and metacal
    format:
      type: metacal
      # Shear responsivity used when mocking the measurement [optional]
      R: [[1,0],[0,1]]
      # Shear step used in finite differencing [optional]
      delta_gamma: 0.01
